name: trs

services:
  db:
    image: postgres:18.0-alpine3.22
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: trs
      POSTGRES_PASSWORD: hunter2
      POSTGRES_DB: trs
    volumes:
      - ./postgres-data:/var/lib/postgresql/18/docker
